# Pandas

Data Engineering 

Data Analyst 

Data Scientist

In [ ]:
# Plain Python way — painful
with open("students.csv", "r") as f:
    lines = f.readlines()

headers = lines[0].strip().split(",")
students = []
for line in lines[1:]:
    values = line.strip().split(",")
    students.append(dict(zip(headers, values)))

# Just to get average score:
scores = [int(s["score"]) for s in students]
avg = sum(scores) / len(scores)

In [1]:
import pandas as pd

In [ ]:
!pip install pandas

In [ ]:
# Two main tools 

# Series -- one column of data 
# DataFrames -- full table (rows + columns)

In [2]:
# single column 

scores = pd.Series([85,100,95,15,69])
print(scores)

0     85
1    100
2     95
3     15
4     69
dtype: int64

In [3]:
print(scores[1])

100

In [7]:
print(scores.sum())
print(scores.max())
print(scores.count())

364
100
5

In [10]:
print(scores.describe())

count      5.000000
mean      72.800000
std       34.412207
min       15.000000
25%       69.000000
50%       85.000000
75%       95.000000
max      100.000000
dtype: float64

In [2]:
data = {"Ali":85,"Ayan":50,"Ulwan":78}
data_series = pd.Series(data)

In [3]:
data_series

Ali      85
Ayan     50
Ulwan    78
dtype: int64

In [4]:
data_series['Ali']

np.int64(85)

In [5]:
# Student 1 -- Ayan -- Maths, python

In [6]:
# DataFrame -- A Dataframe is a 2D table -- that contains rows and columns 
# just like a spreadsheet - excel

In [9]:
data = {
    "name": ["Ayan", "Ali","Misha","Ulwan","Zainab"],
    "age": [55,12,23,29,30,],
    "city":["Karachi","Hyderabad","Quetta","Hyderabad","Quetta"],
    "Scores":[20,50,9,45,50]
}

df = pd.DataFrame(data)
print(df)

     name  age       city  Scores
0    Ayan   55    Karachi      20
1     Ali   12  Hyderabad      50
2   Misha   23     Quetta       9
3   Ulwan   29  Hyderabad      45
4  Zainab   30     Quetta      50

In [23]:
df = pd.read_csv("students.csv")
print(df)

     Name  Age       City  Scores
0    Ayan   55    Karachi      20
1     Ali   12        NaN      50
2   Misha   23     Quetta       9
3   Ulwan   29  Hyderabad      45
4  Zainab   30     Quetta      50

In [ ]:
df.describe()

             Age     Scores
count   5.000000   5.000000
mean   29.800000  34.800000
std    15.801899  19.044684
min    12.000000   9.000000
25%    23.000000  20.000000
50%    29.000000  45.000000
75%    30.000000  50.000000
max    55.000000  50.000000

In [ ]:
# print(df.head(2)) # by deafult shows 5 rows 
# print(df.tail(2))
# print(df.shape) # (rows,columns)
# print(df.columns)
# print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    4 non-null      object
 3   Scores  5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes
None

In [25]:
df

     Name  Age       City  Scores
0    Ayan   55    Karachi      20
1     Ali   12        NaN      50
2   Misha   23     Quetta       9
3   Ulwan   29  Hyderabad      45
4  Zainab   30     Quetta      50

Accessing Columns

In [ ]:
# print(df["Name"]) # to get single column
print(df["City"])

0      Karachi
1          NaN
2       Quetta
3    Hyderabad
4       Quetta
Name: City, dtype: object

In [33]:
# To get more than one column -- use double brackets [[]]
print(df[["Name","City","Age"]])

     Name       City  Age
0    Ayan    Karachi   55
1     Ali        NaN   12
2   Misha     Quetta   23
3   Ulwan  Hyderabad   29
4  Zainab     Quetta   30

Accessing Rows

In [37]:
# By position - iloc

# print(df.iloc[0]) # first row 
# print(df.iloc[2]) # third row 

print(df.iloc[0:3]) # included:excluded

    Name  Age     City  Scores
0   Ayan   55  Karachi      20
1    Ali   12      NaN      50
2  Misha   23   Quetta       9

Adding a new column

In [40]:
df["Score_double"] = df["Scores"] * 3
print(df)

     Name  Age       City  Scores  Score_double
0    Ayan   55    Karachi      20            60
1     Ali   12        NaN      50           150
2   Misha   23     Quetta       9            27
3   Ulwan   29  Hyderabad      45           135
4  Zainab   30     Quetta      50           150

In [42]:
# add a column on the basis of any condition 
df["Passed"] = df["Scores"] >= 30

print(df)

     Name  Age       City  Scores  Score_double  Passed
0    Ayan   55    Karachi      20            60   False
1     Ali   12        NaN      50           150    True
2   Misha   23     Quetta       9            27   False
3   Ulwan   29  Hyderabad      45           135    True
4  Zainab   30     Quetta      50           150    True

Filtering Rows

In [43]:
high = df[df["Score_double"] > 100 ]
high

     Name  Age       City  Scores  Score_double  Passed
1     Ali   12        NaN      50           150    True
3   Ulwan   29  Hyderabad      45           135    True
4  Zainab   30     Quetta      50           150    True

In [44]:
quetta = df[df["City"] == "Quetta"]
quetta

     Name  Age    City  Scores  Score_double  Passed
2   Misha   23  Quetta       9            27   False
4  Zainab   30  Quetta      50           150    True

### Sorting

In [45]:
# Ascending 
df_sorted =  df.sort_values("Scores")
print(df_sorted)

     Name  Age       City  Scores  Score_double  Passed
2   Misha   23     Quetta       9            27   False
0    Ayan   55    Karachi      20            60   False
3   Ulwan   29  Hyderabad      45           135    True
1     Ali   12        NaN      50           150    True
4  Zainab   30     Quetta      50           150    True

In [47]:
# Descending 
df_sorted =  df.sort_values("Scores", ascending=False) 
print(df_sorted)

     Name  Age       City  Scores  Score_double  Passed
1     Ali   12        NaN      50           150    True
4  Zainab   30     Quetta      50           150    True
3   Ulwan   29  Hyderabad      45           135    True
0    Ayan   55    Karachi      20            60   False
2   Misha   23     Quetta       9            27   False

In [49]:
# sort by multiple columns 
df_sorted = df.sort_values(["Scores","Age"],ascending = [False,False])
print(df_sorted)

     Name  Age       City  Scores  Score_double  Passed
4  Zainab   30     Quetta      50           150    True
1     Ali   12        NaN      50           150    True
3   Ulwan   29  Hyderabad      45           135    True
0    Ayan   55    Karachi      20            60   False
2   Misha   23     Quetta       9            27   False

In [51]:
# Save back to csv
df.to_csv("students_transformed.csv",index=False)

In [57]:
import pandas as pd
import numpy as np # matplotlib/seaborn

messy = {
    "name"  : ["Ali", "Sara", None, "Zara", "Hassan", "Sara"],
    "age"   : [22, None, 23, 21, 24, 20],
    "city"  : ["Karachi", "Lahore", "Islamabad", None, "Peshawar", "Lahore"],
    "score" : [85, 92, None, 65, 90, 92]
}

df2 = pd.DataFrame(messy)
print(df2)

     name   age       city  score
0     Ali  22.0    Karachi   85.0
1    Sara   NaN     Lahore   92.0
2    None  23.0  Islamabad    NaN
3    Zara  21.0       None   65.0
4  Hassan  24.0   Peshawar   90.0
5    Sara  20.0     Lahore   92.0

Real data is always messy:

Missing values (empty cells)

Wrong data types

Duplicate rows

Inconsistent text

In [59]:
# detect null values
print(df2.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    5 non-null      object
 1   age     5 non-null      float64
 2   city    5 non-null      object
 3   score   5 non-null      float64
dtypes: float64(2), object(2)
memory usage: 324.0+ bytes
None

In [62]:
# print(df.isnull())
print(df2.isnull().sum())

name     1
age      1
city     1
score    1
dtype: int64

In [63]:
# Clean null values - drop 

df_clean = df2.dropna()
print(df_clean)

     name   age      city  score
0     Ali  22.0   Karachi   85.0
4  Hassan  24.0  Peshawar   90.0
5    Sara  20.0    Lahore   92.0

In [64]:
# drop specfic name
df_clean = df2.dropna(subset=["name"])

In [65]:
df_clean

     name   age      city  score
0     Ali  22.0   Karachi   85.0
1    Sara   NaN    Lahore   92.0
3    Zara  21.0      None   65.0
4  Hassan  24.0  Peshawar   90.0
5    Sara  20.0    Lahore   92.0

In [66]:
df_filled = df2.fillna("Unknown")
print(df_filled)

      name      age       city    score
0      Ali     22.0    Karachi     85.0
1     Sara  Unknown     Lahore     92.0
2  Unknown     23.0  Islamabad  Unknown
3     Zara     21.0    Unknown     65.0
4   Hassan     24.0   Peshawar     90.0
5     Sara     20.0     Lahore     92.0

In [ ]:
# fill the null score with the avg value of the scores
# rename the columns 
# change data types